[package]
name = "rdb"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
sea-orm.workspace = true
log.workspace = true
dotenv.workspace = true
tokio.workspace = true
thiserror.workspace = true
env_config_parse.workspace = true

[features]
rpm_build = []
docker_build = []