[package]
name = "jwt"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
openssl.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
base64.workspace = true