[package]
name = "distributed_lock"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
log.workspace = true
thiserror.workspace = true
redis.workspace = true
cache.workspace = true