[package]
name = "config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
serde.features = ["derive"]
serde_yaml.workspace = true
serde_json.workspace = true
config_manager.workspace = true
cron.workspace = true

[dev-dependencies]
tempfile = "3.3"
