agent:
  listen_enabled: false
  listen_address: "127.0.0.1"   # The agent runs with root privileges and only supports IP listening on this node.
  listen_port: 8088
  uuid: "a4e7c719-6b05-4ac6-b95a-7e71a9d6f9d5"  # Unique agent identifier
  user_id: "test_01" # Unique user identifier
  apikey:

server:
  server_url: "https://127.0.0.1:8443"  # Base URL, API paths will be automatically appended
  tls:
    cert_path: "/etc/attestation_agent/certs/client.crt"
    key_path: "/etc/attestation_agent/certs/client.key"
    ca_path: "/etc/attestation_server/certs/ca.crt"

logging:
  level: "info"  # Available values: trace, debug, info, warn, error
  file: "/var/log/ra-agent.log"

plugins:
  - name: "tpm_boot"
    path: "/usr/lib64/libtpm_boot_attester.so"
    policy_id: []
    enabled: true
    params:
      attester_type: "tpm_boot"
      tcti_config: "device" # options: device, mssim, swtpm, tabrmd, libtpm
      ak_certs:
        - cert_type: "iak"
          ak_handle: 0x81010020
          ak_nv_index: 0x150001b
      pcr_selections: 
        banks: [0, 1, 2, 3, 4, 5, 6, 7] # options: 0-23
        hash_alg: "sha256" # options: sha1, sha256, sha384, sha512, sm3
      quote_signature_scheme: # optional
        signature_alg: "rsapss" # options: rsapss, rsassa, ecdsa; The value needs to be consistent with the signing algorithm of the AK key.
        hash_alg: "sha256" # options: sha1, sha256, sha384, sha512, sm3
      log_file_path: "/sys/kernel/security/tpm0/binary_bios_measurements"

  - name: "tpm_ima"
    path: "/usr/lib64/libtpm_ima_attester.so"
    policy_id: []
    enabled: false
    params:
      attester_type: "tpm_ima"
      tcti_config: "device" # options: device, mssim, swtpm, tabrmd, libtpm
      ak_certs:
        - cert_type: "iak"
          ak_handle: 0x81010020
          ak_nv_index: 0x150001b
      pcr_selections: 
        banks: [10] # options: 10
        hash_alg: "sha256" # options: sha1, sha256, sha384, sha512, sm3
      quote_signature_scheme: # optional
        signature_alg: "rsapss" # options: rsapss, rsassa, ecdsa; The value needs to be consistent with the signing algorithm of the AK key.
        hash_alg: "sha256" # options: sha1, sha256, sha384, sha512, sm3
      log_file_path: "/sys/kernel/security/ima/ascii_runtime_measurements"

  - name: "virt_cca"
    path: "/usr/lib64/libvirt_cca_attester.so"
    policy_id: []
    enabled: false
    params:
      attester_type: "virt_cca"
      ima_log_file_path: "/sys/kernel/security/ima/ascii_runtime_measurements"
      ccel_data_path: "/sys/firmware/acpi/tables/data/CCEL"

schedulers:
  - name: "challenge"      # Remote attestation task
    retry_enabled: true
    intervals: 86400        # 24 * 60 * 60 = 86400 = 1 day
    initial_delay:                   # Random delay configuration at startup
      min_seconds: 1                 # Minimum delay 1 second
      max_seconds: 60               # Maximum delay 60 seconds
    max_retries: 1
    enabled: true

  - name: "config_sync"     # Configuration synchronization task
    retry_enabled: false    # Temporarily disabled
    intervals: 300          # Execute every 5 minutes
    enabled: false           # No initial_delay configuration means no initial random delay is needed
    
