[package]
name = "KeyManager"
version = "0.1.0"
edition = "2024"

[dependencies]
# web框架
actix-web="4.9.0"
tokio="1.43.0"
# 文件上传
actix-multipart="0.7.2"
# json序列化工具
serde_json="1.0.138"
# 日志框架
log="0.4.25"
